### PR TITLE
011_data.preparation.ipynb

### PR DESCRIPTION
**Pull request by HafizAhmadHassan**

### CODE REVIEW

**Comment by oguiza** [comment]
Hi @HafizAhmadHassan,
Thanks for submitting this PR. 
Could you please explain what problem you are trying to address with it?

**Comment by HafizAhmadHassan** [comment]
Hi Thankyou so much sorry for being late.. Actually this functions is basically oversampling method with different percentages like if percentage = 0.3 then the class which contains (less data) will be oversampled by 0.3* percent of class having most instances

**Comment by oguiza** [comment]
Hi @HafizAhmadHassan,
Could you please provide an example to explain where this type of functionality may be useful?
There's already some functionality in tsai that allows you to balance 
```bash
new_idxs = balance_idx(idxs, shuffle=False, random_state=None, verbose=False)
```

**Comment by oguiza** [comment]
I'll close this PR due to a lack of response.

**Pull request closed without merging**
