### PR TITLE
Fixing names

### PR DESCRIPTION
**Pull request by geoHeil**
here the improved PR for real with both NB changes and updated docks

### CODE REVIEW

**Comment by geoHeil** [comment]
I tried to rebase but somehow nbdev is not fully re-building the documentation only the latest changes. can I somehow force it to rebuild everything?

**Comment by oguiza** [comment]
> I tried to rebase but somehow nbdev is not fully re-building the documentation only the latest changes. can I somehow force it to rebuild everything?

Yes, you can run this in your terminal:

```
nbdev_build_docs -- force_all True
```
I'm not sure why you have created a new PR. This one has some conflicting files. Run the code above and commit again within the same branch. There's no need to create a new PR.

**Comment by geoHeil** [comment]
Solved. The other one was simply edited directly in the GitHub UI - I did not know where to connect it to my fork. Should be all set and hopefully fine now.

**Comment by oguiza** [comment]
Ok, merged. Thanks, @geoHeil!

**Pull request merged**
