### PR TITLE
Tutorial notebook using Optuna

### PR DESCRIPTION
**Pull request by dnth**
I have added a tutorial notebook that showcases how to use TSAI with Optuna for hyperparameter optimization.
Would love to hear your feedbacks as this is only my first pull request on Github.
Thank you for the efforts in building TSAI. I would love to contribute more as I learn.

### CODE REVIEW

**Comment by oguiza** [comment]
Hi @dnth, 

Sorry for not getting back to you earlier. I plan to review your notebook and provide feedback early next week.

**Comment by dnth** [comment]
No worries @oguiza just take your time. Initially I was a little worried because there's no commits by you in tsai and I thought something happened. But glad to see you're back!

**Comment by oguiza** [comment]
Hi @dnth,

Thanks again for submitting this PR and for your patience!! :)

Before anything else, you should replace my name with yours: created by Ignacio Oguiza - email: timeseriesAI@gmail.com
(You can leave the email if you want). You are the one who's created this notebook!!

I have 3 types of comments: general, requests and suggestions/ ideas.

- requests are things that must be changed to approve the PR
- suggestions are ideas of how I think the notebook might be improved. It's up to you to decide if you change it or not. 

General: 

- I've learned a lot by reviewing this PR. Thanks for creating this PR!!
- I'd never used Optuna before. But now that I've used it I love it! I'll start using it in my next project. 
- I like the approach you took in the notebook. It's an easy task so that the focus is on how Optuna works. 
- I also like your idea of establishing a baseline for benchmarking. 
- You are making use of the new TSClassifier API. Great!
- The outcome is also great! I think it's a very good way to communicate how you can easily improve your outcome.  


Requests: 

- You should replace: 

```
# stable = True # True: latest version, False: stable version
# import sys
# ISCOLAB = 'google.colab' in sys.modules
# if ISCOLAB:
#     if stable: 
#         !pip install tsai -Uqq
#     else:
#         !pip install -Uqq git+https://github.com/timeseriesAI/tsai.git
```

by 

```
# ## NOTE: UNCOMMENT AND RUN THIS CELL IF YOU NEED TO INSTALL/ UPGRADE TSAI
# stable = False # True: latest version from github, False: stable version in pip
# if stable: 
#     !pip install tsai -U >> /dev/null
# else:      
#     !pip install git+https://github.com/timeseriesAI/tsai.git -U >> /dev/null
# ## NOTE: REMEMBER TO RESTART (NOT RECONNECT/ RESET) THE KERNEL/ RUNTIME ONCE THE INSTALLATION IS FINISHED
```

and 

```
import tsai
from tsai.all import *
print('tsai       :', tsai.__version__)
print('fastai     :', fastai.__version__)
print('fastcore   :', fastcore.__version__)
print('torch      :', torch.__version__)
```

by 

```
from tsai.all import *
p = !python  -V
print(f'python         : {p[0].split(" ")[1]}')
print(f'tsai           : {tsai.__version__}')
print(f'fastai         : {fastai.__version__}')
print(f'fastcore       : {fastcore.__version__}')
print(f'torch          : {torch.__version__}')
print(f'#cpus          : {cpus}')
iscuda = torch.cuda.is_available()
print(f'device         : {device} ({torch.cuda.get_device_name(0)})' if iscuda else f'device         : {device}')
```

It's the standard code I use and it's a bit more informative (you may have copied it from an older notebook). 
When users submit an issue it helps to understand what they are using.

- I would replace this: 
```
dsid = 'NATOPS' 
X, y, splits = get_UCR_data(dsid, return_split=False)

# Old API
tfms  = [None, [Categorize()]]
dsets = TSDatasets(X, y, tfms=tfms, splits=splits, inplace=True)
dls   = TSDataLoaders.from_dsets(dsets.train, dsets.valid, bs=[64, 128], batch_tfms=[TSStandardize()], num_workers=0)
model = InceptionTimePlus(dls.vars, dls.c)
learn = Learner(dls, model, metrics=accuracy)
learn.fit_one_cycle(5, lr_max=1e-3)
learn.plot_metrics()

# New API
# learn = TSClassifier(X, y, splits=splits, bs=[64, 128], batch_tfms=[TSStandardize()], arch=InceptionTimePlus, metrics=accuracy)
# learn.fit_one_cycle(5, lr_max=1e-3)
# learn.plot_metrics()
```

by this: 

```
X, y, splits = get_UCR_data('NATOPS', split_data=False)
learn = TSClassifier(X, y, splits=splits, bs=[64, 128], batch_tfms=TSStandardize(by_sample=True), arch=InceptionTimePlus, metrics=accuracy, cbs=ShowGraph())
learn.fit_one_cycle(5, lr_max=1e-3)
```
ShowGraph includes by default the metrics when training is finished.

Suggestions:

- I'd use a different dataset where you can demonstrate SOTA performance. NATOPS SOTA is >95%. But I understand this is being used to demonstrate the functionality. I'll leave it up to you. 
- I'd include some explanation on the search space definition. I've taken it from the Optuna docs. It allows you to have a cleaner objective function.
- I'd also do the same with the  FastAIPruningCallback.
- There's a way to train a model without printing anything during training. It may be useful to reduce the length of the nb.
- I've added an option to create a script (which can be reused). In this way you can run the HPO within your notebook or from your terminal. The main function offers some parameters. 
- One of the options includes plots. They are easy to understand, and I believe they add value. 
- I've also enabled the progress bar so that we have an idea how long the HPO might take.

Questions: 

- When you re-train the model with the best parameters, you don't need to use FastAIPruningCallback, do you? 

I've created a (gist)[https://colab.research.google.com/gist/oguiza/16d3570c73c4614694663f9bd6ed9bd7/optuna_hpo_draft.ipynb] with all these ideas.

Take your time to update the current PR. And thanks again for your submission!!!

**Comment by dnth** [comment]
Thank you for helping to review this PR. I am incredibly happy to contribute and am learning a lot with this myself. I will incorporate your suggestions in!

**Comment by oguiza** [comment]
> Thank you for helping to review this PR. I am incredibly happy to contribute and am learning a lot with this myself. I will incorporate your suggestions!

I'm very glad to hear that!! 😃

I think that the best way to learn something is to teach it. To prepare a tutorial nb is really helpful to learn a lot about a topic. I've also learned a lot by working on it. 

I wasn't very happy with the notebook I sent you yesterday, and have refactored it a bit. I believe [this](https://colab.research.google.com/gist/oguiza/ffb72bc73dcf47826b9599aeee8748bc/optuna_hpo_draft2.ipynb) is much easier to use from a user perspective. Please, let me know your thoughts. 

We could add the run_study code to fastai (although that'd mean we create an extra dependency to optuna, but I think it might be useful). Let's see how this pans out in the end.

**Comment by oguiza** [comment]
> Thank you for helping to review this PR. I am incredibly happy to contribute and am learning a lot with this myself. I will incorporate your suggestions!

Hi @dnth,

I hope are well.

Just wanted to follow up on this. I'm putting together a tutorial on how to perform hyperparameter optimization using W&B. I'd like to know when you think you'll be ready to submit the commit to update this PR. I'd like to release both nbs at the same time (more or less). 

BTW, after having used both for some time, I have to say I like Optuna better. W&B has the benefit of Experiment tracking, but in therm of pure HPO, I got better results with Optuna. Do you also have experience with W&B?

**Comment by vrodriguezf** [comment]
Hi,

I normally use wandb sweeps for their simplicity. Basically, if you arrange the notebook properly, you don't have to change or add any extra line code in your notebook for the hyperparameter search, you can just config the search in their GUI and run the sweep agent as a command in a terminal.

**Comment by dnth** [comment]
> > Thank you for helping to review this PR. I am incredibly happy to contribute and am learning a lot with this myself. I will incorporate your suggestions!
> 
> Hi @dnth,
> 
> I hope are well.
> 
> Just wanted to follow up on this. I'm putting together a tutorial on how to perform hyperparameter optimization using W&B. I'd like to know when you think you'll be ready to submit the commit to update this PR. I'd like to release both nbs at the same time (more or less).
> 
> BTW, after having used both for some time, I have to say I like Optuna better. W&B has the benefit of Experiment tracking, but in therm of pure HPO, I got better results with Optuna. Do you also have experience with W&B?

Hi @oguiza, I foresee will be able to update within the next 2 days.. Thank you!

**Comment by dnth** [comment]
Hi @oguiza I have added in your requests into the notebook. I find that your colab notebook is really comprehensive and I don't know how to slot into this notebook. Feel free to add the parts from your colab notebook into this one. Thank you for the hard work.

**Comment by oguiza** [comment]
> Hi @oguiza I have added in your requests into the notebook. I find that your colab notebook is really comprehensive and I don't know how to slot into this notebook. Feel free to add the parts from your colab notebook into this one. Thank you for the hard work.

Thanks for submitting a new commit @dnth!

I've reviewed your proposal and looks ok to me. I see you prefer to simplify the nb which is fine. 

I've made a few changes to:

- standardize things like imports. 
- removed the random_seed function and used fastai's set_seed (which does the same I believe). 
- re-run the notebook because all outputs had been removed. 

Please, take a look at it ([gist](https://colab.research.google.com/gist/oguiza/c021ef7d1a83b2b3e2f045ccc199ed30/12_hyperparameter_optimization_with_optuna.ipynb)), and if you are ok, send me a new commit with the final notebook. 

Thanks again for putting this together!!

**Comment by dnth** [comment]
> > Hi @oguiza I have added in your requests into the notebook. I find that your colab notebook is really comprehensive and I don't know how to slot into this notebook. Feel free to add the parts from your colab notebook into this one. Thank you for the hard work.
> 
> Thanks for submitting a new commit @dnth!
> 
> I've reviewed your proposal and looks ok to me. I see you prefer to simplify the nb which is fine.
> 
> I've made a few changes to:
> 
> * standardize things like imports.
> * removed the random_seed function and used fastai's set_seed (which does the same I believe).
> * re-run the notebook because all outputs had been removed.
> 
> Please, take a look at it ([gist](https://colab.research.google.com/gist/oguiza/c021ef7d1a83b2b3e2f045ccc199ed30/12_hyperparameter_optimization_with_optuna.ipynb)), and if you are ok, send me a new commit with the final notebook.
> 
> Thanks again for putting this together!!

Hi @oguiza have updated the notebook following your gist :)

**Comment by oguiza** [comment]
Thanks @dnth for submitting the PR again. It looks good to me. 

I've started the merge process, but the check have failed. Reason is: 
```
!!! Detected unstripped out notebooks
!!!Remember to run nbdev_install_git_hooks
```
Did you run nbdev_install_git_hooks when you created your repo? Unless that step is done, I cannot merge anything. 
There are more details in the CONTRIBUTING.md file.

**Comment by dnth** [comment]
> Thanks @dnth for submitting the PR again. It looks good to me.
> 
> I've started the merge process, but the check have failed. Reason is:
> 
> ```
> !!! Detected unstripped out notebooks
> !!!Remember to run nbdev_install_git_hooks
> ```
> 
> Did you run nbdev_install_git_hooks when you created your repo? Unless that step is done, I cannot merge anything.
> There are more details in the CONTRIBUTING.md file.

Noted there :))

**Comment by oguiza** [comment]
I'm sorry, @dnth, but I keep getting the same issue: 

```
!!! Detected unstripped out notebooks
17
!!!Remember to run nbdev_install_git_hooks
18
Error: Process completed with exit code 1.
```

Have you run it in the your local repo?

**Comment by dnth** [comment]
I'm sorry for the hassle @oguiza. I have run the nb_dev_install_git_hooks again on my local repo. 

On another note, this pull request was created before the release of the contributing guide on tsai. Back then i forked the tsai repo and then work on the notebook. The pull request was created through the internet browser. Could there be an issue with this? Should I create another pull request following the official contribution guide instead?

**Comment by oguiza** [comment]
> I'm sorry for the hassle @oguiza. 

No need to worry about this @dnth. I really appreciate your interest in contributing to tsai. 😃

> On another note, this pull request was created before the release of the contributing guide on tsai. ...
Should I create another pull request following the official contribution guide instead?

I think it'd be good to do that. nbdev is a great tool, but it requires you to follow certain steps as described in the contribution guidelines. You can just make sure you save the notebook somewhere safe and follow the steps in the guide. In step 3 of 'Creating a PR' just add the notebook to the tutorial, and continue with the rest of steps. It shouldn't take too long, and you will have an environmente ready for you next contributions. 

Please, let me know if you find any issues.

**Pull request closed without merging**
