### PR TITLE
fixed MixedDataLoader and add tutorial

### PR DESCRIPTION
**Pull request by Wabinab**
When one tries to make prediction there are some errors with `outs` on `__iter__` because it doesn't present so one adds a try-except block to fix that. 

One problem with the notebook is one haven't add test because one doesn't know how to deal with different dataloaders. For our current function, if we are to have multiple dataloaders, it suspects that the function `MixedDataLoader.new` requires rewrite, because each `MixedDataLoader.loaders` will take in different `test_ds` (check out the tutorial one wrotes and the ones oguida wrotes on predictions for more idea of what one is talking about), such that you could pass in multiple `test_ds`, each for each loaders, rather than passing all datasets to all dataloaders (which is what the current `new` function does). Do tell me if we would like to make changes on that and one will require experimentation to see how it works first. 

Another thing one make changes to the test is `y.long()` to `y.long().cpu()` as it was assigned to cuda on my VM when running the notebook. Also one might consider adding an empty "export" folder to "nbs" or else there will be an error when trying to do `torch.save("export/something.pth")`. 

N.B. Particularly using this method of prediction because `learn.get_X_preds()` doesn't work. 

Thanks.

### CODE REVIEW

**Comment by Wabinab** [comment]
When one tries to make prediction there are some errors with `outs` on `__iter__` because it doesn't present so one adds a try-except block to fix that. 

One problem with the notebook is one haven't add test because one doesn't know how to deal with different dataloaders. For our current function, if we are to have multiple dataloaders, it suspects that the function `MixedDataLoader.new` requires rewrite, because each `MixedDataLoader.loaders` will take in different `test_ds` (check out the tutorial one wrotes and the ones oguida wrotes on predictions for more idea of what one is talking about), such that you could pass in multiple `test_ds`, each for each loaders, rather than passing all datasets to all dataloaders (which is what the current `new` function does). Do tell me if we would like to make changes on that and one will require experimentation to see how it works first.

**Comment by oguiza** [comment]
Hi @Wabinab,
I'm really sorry for my very late response. But I'd like to better understand the issue you are trying to fix. 
Is there any chance you can post a code snippet to clarify what is the issue you have found?

**Comment by Wabinab** [comment]
Ok on the "fix" side of this issue, if you check this https://github.com/timeseriesAI/tsai/blob/main/tsai/data/mixed.py on the `__iter__` (so I'll just post the code here)

```python
def __iter__(self):
        z = zip(*[_loaders[i.fake_l.num_workers == 0](i.fake_l) for i in self.loaders])
        for b in z:
            inps = []
            outs = []
            if self.device is not None:
                b = to_device(b, self.device)
            for batch, dl in zip(b, self.loaders):
                if hasattr(dl, 'idxs'): self.idxs = dl.idxs
                if hasattr(dl, 'input_idxs'): self.input_idxs = dl.input_idxs
                batch = dl.after_batch(batch)
                inps += batch[:dl.n_inp]
                outs += batch[dl.n_inp:]
            inps = tuple([tuple(L(inps)[idx]) if isinstance(idx, list) else inps[idx]
                          for idx in self.x_idxs]) if len(self.x_idxs) > 1 else tuple(L(outs)[self.x_idxs][0])
            outs = tuple(L(outs)[self.y_idxs]) if len(self.y_idxs) > 1 else L(outs)[self.y_idxs][0]
            yield inps, outs
```

The last three lines of code, you specify the `inps` and `outs` and `yield inps, outs`, but `outs` **is optional**. So that's what one's trying to fix. 

P.S. One didn't mention it for quite long because when one checks your side branch (It's the development branch that you're developing, it's called the *static_data* branch) one saw you fix it with 

```python
if len(self.y_idxs) == 0: 
    yield tuple((inps,))
```

which is also fine. One just took it a different way of 
```python
try: 
    outs = ...
    yield inps, outs
except Exception: 
    yield inps
```

**Comment by oguiza** [comment]
Ok, thanks for the explanation.
I'm not going to merge the static_data branch because I found an easier approach. 
I've just pulled the section you mentioned and added it to the current code. So this should be the issue. 
I prefer this solution:

```bash 
def __iter__(self):
        z = zip(*[_loaders[i.fake_l.num_workers == 0](i.fake_l) for i in self.loaders])
        for b in z:
            inps = []
            outs = []
            if self.device is not None:
                b = to_device(b, self.device)
            for batch, dl in zip(b, self.loaders):
                if hasattr(dl, 'idxs'): self.idxs = dl.idxs
                if hasattr(dl, 'input_idxs'): self.input_idxs = dl.input_idxs
                batch = dl.after_batch(batch)
                inps += batch[:dl.n_inp]
                outs += batch[dl.n_inp:]
            inps = tuple([tuple(L(inps)[idx]) if isinstance(idx, list) else inps[idx]
                          for idx in self.x_idxs]) if len(self.x_idxs) > 1 else tuple(L(outs)[self.x_idxs][0])
            if len(self.y_idxs) == 0: # based on issue identified by @Wabinab https://github.com/timeseriesAI/tsai/pull/229
                yield tuple((inps,))
            outs =  tuple(L(outs)[self.y_idxs]) if len(self.y_idxs) > 1 else L(outs)[self.y_idxs][0]
            yield inps, outs
```
to using the try/ except since it's something that's already known. 
I've just deployed the solution above so I believe this issue can be closed. 
Please reopen it if necessary.

**Pull request closed without merging**
