### PR TITLE
Fix for issue #181

### PR DESCRIPTION
**Pull request by rkainkaryam**
Added freq option to add_missing_timestamps function in data preparation; included test examples with freq option; updated function docs to recommend no duplicate timestamps in a group

### CODE REVIEW

**Comment by oguiza** [comment]
Hi @rkainkaryam,

Sorry for my late review, but I couldn't do it before.

Thanks again for your interest in tsai and for taking the time to create this PR. 

I've reviewed it and have a few comments: 

1. The changes you made to the add_missing_timestamps code look good to me. 
2. There are 2 lines of code that could be removed: 
   ```
   cols = df.columns
   ```

    and 

    ```
    df = df[cols]
    ```
I've noticed they are not required. 

3. I've seen you have documented alternative scenarios, which is great. Bear in mind that whatever we add in the notebooks will later show up in the documentation. By adding these scenarios you help others better understand how this function works. 
4. Something important I'm missing are tests. The idea throughout tsai is that tests are handled automatically. So if a change breaks something the test fails. It'd be good to confirm that the output of the formula is exactly what we expect to get. 

Tests need to pass as quickly as possible to avoid an excessive delay during testing.

Types of tests I've used in the past are: 

assert 1+1,2
arr = np.random.rand(10,2)
test_eq(arr, arr) # test equal
test_close(tensor(arr).sum(), arr.sum(), eps=1e-5) # test close within an margin
test_ne(1, 2) # not equal
test_gt(2,1) # greater than
test_lt(1,2) # less than

We can even add tests knowing that the function will fail with those args and kwargs.

And you can add text to explain the tests (this will be shown in the documentation).

All tests are added after the code that needs to be tested. In this way, when the notebook is run end to end, we know if the tests pass or fail. It's a very convenient way to ensure everything works are expected. When bugs are identified, new tests can be added. 

In this case I'd like to make sure not only that the function produces an output, but also that the output is the expected one.

I've added examples of tests in this [colab nb](https://colab.research.google.com/gist/oguiza/0ee4d2e0fc75b3bdedd5b104db187315/add_missing_timestamps.ipynb#scrollTo=_uENF3dDkwCI). As you can see, if the tests pass, we can be certain the function is working well. 

It'd be good if you added these or other similar tests to the PR. 

You can follow the updated CONTRIBUTION.mb instructions to update the pr with a new commit. 

Please, let me know if you have any issue.

**Comment by rkainkaryam** [comment]
Hi @oguiza 

I added tests for all the `add_missing_timestamp` use cases (including the older ones not using the `freq` option)

Additionally, while I was adding tests for the `add_delta_timestamp_cols`, I fixed the follow bug with `groupby` (which was using a hard-coded values `user_id` instead of the parameter `groupby`):

[Current line](https://github.com/timeseriesAI/tsai/blob/7bb5a5e46d0e857214e0297167c8b37ba44b9785/tsai/data/preparation.py#L282):
`forward_time_gaps = df[cols].groupby(df['user_id']).apply(lambda x: forward_gaps(x.values.transpose(1,0)[None], nan_to_num=np.nan, normalize=normalize))`

Fix:
`forward_time_gaps = df[cols].groupby(df[groupby]).apply(lambda x: forward_gaps(x.values.transpose(1,0)[None], nan_to_num=np.nan, normalize=normalize))`
      
Please let me know if there are any other changes/updates for this PR.

**Comment by oguiza** [comment]
Hi @rkainkaryam,

Thanks for adding all tests. They look good to me now. I've noticed you've added tests for dates and timestamps. Great!
One of the benefits of adding tests in the notebooks is that they will also become part of the documentation. In that way, it's easier for users to understand how the functionality works. 

And good catch on the add_delta_timestamp_cols function!! 

I'll go ahead and merge this code.

**Comment by oguiza** [comment]
Well, I've just merged the code. Everything's working fine. 
You can check the changes made in the documentation [here](https://timeseriesai.github.io/tsai/data.preparation.html#add_missing_timestamps).

Thanks a lot, @rkainkaryam for your identifying the issue, learning how to create a PR in tsai, creating the code, and adding tests.  Glad to have you now as an official tsai contributor!! 🤗

**Pull request merged**
