### PR TITLE
autoformer implementation

### PR DESCRIPTION
**Pull request by celtics1863**
add model only (without test)

### CODE REVIEW

**Comment by celtics1863** [comment]
> add model only (without test)

for #401

**Comment by oguiza** [comment]
Hi @celtics1863,
Thanks for submitting this PR. 
I’ve looked though it but couldn’t actually find an autoformer notebook. Am I missing anything?

**Comment by oguiza** [comment]
Hi @celtics1863,
Thanks again for submitting this PR.
Do you  have any plans to add the autoformer model to it? Or should I close this PR?

**Comment by oguiza** [comment]
Hi @celtics1863, 
I hope you're doing well.
I'll go ahead and close this long-standing open PR since I haven't seen any progress in the last few months. 
Having said that, I'm open to receiving PRs for this or any other interesting time series, deep learning models.

**Pull request closed without merging**
