### PR TITLE
Add Optuna tutorial notebook

### PR DESCRIPTION
**Pull request by dnth**
tests are passing on cuda device too

### CODE REVIEW

**Comment by oguiza** [comment]
Hi @dnth, 
Thanks for resubmitting this PR again. I’ve run the checks in GitHub and get this message: 
Detected unstripped out notebooks
17
!!!Remember to run nbdev_install_git_hooks

**Comment by dnth** [comment]
The `nbdev_install_git_hooks` is only run once in the beginning right? If we add a new notebook in the branch, must we run `nbdev_install_git_hooks` again?

**Comment by dnth** [comment]
I ran out of idea what is going on 😶‍🌫️ Maybe I should delete the fork on my github and restart afresh?

**Comment by oguiza** [comment]
Hooray, @dnth!!!
I'm not sure what you did in the end, but all tests passed, and the PR is merged!!
Thanks a lot for all the work you've done to create the notebook, and get the PR approved. There were many learnings (at least from my side) that have led to a more robust process now (for example the ability to run tests both on CPU & GPU).  I'd love to hear if you have any suggestions/ recommendations on how to make the process smoother.

**Comment by dnth** [comment]
Yay! I'm so glad it finally worked out! Thank you for your being kind and patient with me along this long process. 
What I did finally was run `nbdev_clean_nbs` after adding the tutorial notebook. I am not sure why this is needed when `nbdev_install_git_hooks` should also clean the notebook? I ran `nbdev_install_git_hooks` countless time and it seems to not clean the newly added tutorial notebook.

Again, thank you @oguiza for your being so encouraging through this PR. You're no doubt one of the kindest person I have met online.

**Comment by oguiza** [comment]
Thank you very much for your comments @dnth! I really appreciate them.
I'm just sorry the process wasn't as smooth as it should have been. I just hope it works better next time!

**Pull request merged**
