### PR TITLE
documentation fix rename num_layers to n_layers

### PR DESCRIPTION
**Pull request by geoHeil**

### CODE REVIEW

**Comment by oguiza** [comment]
Hi @geoHeil,
Thanks for creating this PR. You are correct. It's a typo in the documentation, although the argument in the model seems to be correctly named. 
I have a couple of comments on this PR: 
- I've seen you've only updated the ipynb. That's ok. I'm not sure you've seen the CONTRIBUTING guide. If you have and have installed nbdev, I need you to run the nb until the end. This will also update the .py file. And then you need to run all the commands needed to update the documentation (nbdev_build_docs). It's all documented step by step.
-  I've noticed the same issue in TSTPlus, which is the enhanced version of TST. I'd like to modify it too. It'd be good if you could make the change there as well and make a new commit to the PR. There's no need to create a new one. 

I'll run the tests and merge the PR as soon as I get the new commit. 
Thanks!

**Comment by geoHeil** [comment]
You are correct. Let me prepare the full PR as suggested by you.

**Comment by geoHeil** [comment]
here the new PR: https://github.com/timeseriesAI/tsai/pull/207 / closing this one

**Comment by geoHeil** [comment]
I tried to rebase but somehow nbdev is not fully re-building the documentation only the latest changes. can I somehow force it to rebuild everything?

**Pull request closed without merging**
